### ISSUE TITLE
tilelayer-wms example broken

### ISSUE THREAD

**Issue by DuncanRowland** [jieter/leaflet-headless#20]
The tilelayer-wms example does not work for me (it is failing to complete loading...)

ubuntu@host:~/leaflet-headless/examples/tilelayer-wms$ node index.js 
Saving an image with a WMS layer ...
/home/ubuntu/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:128
    return prev.apply(ctx, arguments);
                ^

Error: Image given has not completed loading
    at CanvasRenderingContext2D.ctx.(anonymous function) [as drawImage] (/home/ubuntu/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:128:17)
    at drawTile (/home/ubuntu/node_modules/leaflet-image/index.js:174:17)
    at Array.forEach (native)
    at Queue.tileQueueFinish [as _call] (/home/ubuntu/node_modules/leaflet-image/index.js:169:18)
    at maybeNotify (/home/ubuntu/node_modules/d3-queue/build/d3-queue.js:109:34)
    at /home/ubuntu/node_modules/d3-queue/build/d3-queue.js:85:14
    at Image.im.onload (/home/ubuntu/node_modules/leaflet-image/index.js:146:17)
    at buffer2image (/home/ubuntu/leaflet-headless/src/image.js:29:25)
    at Request._callback (/home/ubuntu/leaflet-headless/src/image.js:41:13)
    at Request.self.callback (/home/ubuntu/node_modules/request/request.js:186:22)
ubuntu@host:~/leaflet-headless/examples/tilelayer-wms$

**Comment by jieter** [comment]
@DuncanRowland thanks for reporting. This bug report needs some more info, at least the version of node leaflet-headless and jsdom.

Also note that I don't have much time to invest in leaflet-headless for now, so replies might take some time.

**Comment by jieter** [comment]
@DuncanRowland Fixed the example with 91df279
