### ISSUE TITLE
L.imageOverlay() does not work

### ISSUE THREAD

**Issue by nyurik** [jieter/leaflet-headless#7]
L.imageOverlay does not work if inserted before L.geoJson, and does nothing (works but does not draw nor load the image) if used right after.

This is the stack trace (the lines might be slightly off, so I added the actual code line for each)
```
"Image or Canvas expected"
at TypeError (native)
at handlePathRoot (/home/yurik/wmf/kartotherian/kartotherian/node_modules/leaflet-image/index.js:175:13)

   at the line "ctx.drawImage(root, pos.x, pos.y);"
   root is "core.(anonymous function)"
   x and y are valid integers

at pop (/home/yurik/wmf/kartotherian/kartotherian/node_modules/leaflet-image/queue.js:28:14)
at Object.q.defer (/home/yurik/wmf/kartotherian/kartotherian/node_modules/leaflet-image/queue.js:59:11)
at leafletImage (/home/yurik/wmf/kartotherian/kartotherian/node_modules/leaflet-image/index.js:29:20)
at tryCatcher (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/util.js:16:23)
at ret (eval at <anonymous> (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
at addGeoJson (/home/yurik/wmf/kartotherian/kartotherian/node_modules/kartotherian-server/lib/imager.js:71:12)
at /home/yurik/wmf/kartotherian/kartotherian/node_modules/kartotherian-server/lib/imager.js:117:20
at tryCatcher (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/promise.js:500:35)
at Promise._settlePromise (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/promise.js:560:18)
at Promise._settlePromise0 (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/promise.js:605:10)
at Promise._settlePromises (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/promise.js:684:18)
at Promise._fulfill (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/promise.js:629:18)
at PromiseArray._resolve (/home/yurik/wmf/kartotherian/kartotherian/node_modules/bluebird/js/release/promise_array.js:125:19)
```

**Comment by jieter** [comment]
Isn't this just a leaflet-image bug? Let's discuss it there, please reopen if it turns out to be something I can fix in leaflet-headless.

Refs #59

**Comment by nyurik** [comment]
I think this is related to the difference in leaflet version - you use 1beta, and mapbox is using 0.7.7.  Still experimenting with things.

**Comment by jieter** [comment]
ah, yeah, might be.

**Comment by jieter** [comment]
But you just reverted that with #10 too.

**Comment by nyurik** [comment]
oops, didn't mean to add it to the pull request, but i think its better to use older leaflet for now - lots of 3rd party components still depend on it.  Once its stable, we can migrate.  Still experimenting - the Image issue was working for a bit, and then stopped after clean npm install. debugging now.
